version: '3.1'

services:
  chiristopher:
    build: .
    container_name: chiristopher
    volumes:
      - ./db:/app/db/

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./meta/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./statics/:/static/
      - ../prepared_logs/:/logs/
    depends_on:
      - chiristopher
